
// users
export const LOGIN_USER = 'LOGIN_USER';
export const CONFIRM_PHONE_NUMBER = 'CONFIRM_PHONE_NUMBER';
export const LOGOUT_USER = 'LOGOUT_USER';

// cases
export const SET_USERS_CASE = 'SET_USERS_CASE';
export const DELETE_USERS_CASE = 'DELETE_USERS_CASE';

// places visited 
export const SET_PLACES_ON_MAP = 'SET_PLACES_ON_MAP';
export const SET_USERS_PLACES_VISITED = 'SET_USERS_PLACES_VISITED';
export const ADD_USERS_PLACE_VISITED = 'ADD_USERS_PLACE_VISITED';
export const DELETE_USERS_PLACE_VISITED = 'DELETE_USERS_PLACE_VISITED';
export const DELETE_ALL_USERS_PLACES_VISITED = 'DELETE_ALL_USERS_PLACES_VISITED';




